Zms 598
Zimbra/zm-ajax pull request #1
Opened 2017-03-28 22:07 UTC by grishick

- Avoid throwing NPEs if auth token is missing or empty
- Add ability for global admin to flush ACL cache. Currently, this is used only by automated tests to allow /zimbra web app to verify rights of newly created admin accounts
- return BAD_REQUEST for invalid zimlet names and bad zimlet archives

2017-03-28 22:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-ajax?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-ajax?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-ajax?pullRequest=1) it.</sub>

2017-03-29 09:49 UTC, fatkudu commented on src/com/zimbra/webClient/servlet/ServiceServlet.java
> +                } else if ("/flushall".equals(path)) {
Is **flushall** a superset of **flushuistrings** and **flushzimlets**?  If not then I thing something like **flushpermcache** would make it clearer what the API does.

2017-03-29 10:01 UTC, fatkudu requested changes
Consider renaming /flushall

2017-03-29 16:13 UTC, grishick commented
@fatkudu I renamed /flushall to /flushacl

2017-03-29 16:19 UTC, fatkudu approved these changes

2017-03-29 17:00 UTC, plobbes approved these changes

2017-03-29 17:23 UTC, gordyt approved these changes

2017-03-29 17:31 UTC, merged