ZCS-643: Custom checkbox style
Zimbra/zm-ajax pull request #4
Opened 2017-04-12 06:48 UTC by kalpeshhpatel

Changes:
* DwtCheckbox.js: Added custom checkbox styling changes

This changes are covered as part of task https://jira.corp.synacor.com/browse/ZCS-643.

https://jira.corp.synacor.com/browse/ZCS-643

2017-04-12 17:19 UTC, silentsakky commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this._inputIconEl.setAttribute(AjxEnv.isIE ? "htmlFor" : "for", this._inputEl.id);
do we need to set this attribute everytime when checkbox state  changes?

2017-04-12 18:59 UTC, tarangkhandelwal requested changes

2017-04-12 18:59 UTC, tarangkhandelwal commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +DwtCheckbox.prototype.__setCustomCheckboxIcon = function () {
"function" should start from next line.

2017-04-12 18:59 UTC, tarangkhandelwal commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +
extra space here? Ignore if intended.

2017-04-12 18:59 UTC, tarangkhandelwal commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this.CUSTOM_CHECKBOX_STYLE = DwtCheckbox.CUSTOM_CHECKBOX && this.INPUT_TYPE == 'checkbox';
Just to confirm: DwtCheckbox.CUSTOM_CHECKBOX  will always be true as we set it true as default. Should this be this.CUSTOM_CHECKBOX for any child widget inheriting this to disabled the custom behavior?

2017-04-12 19:00 UTC, tarangkhandelwal requested changes
Looks good to me . Just small changes and this is good to go.

2017-04-13 05:09 UTC, kalpeshhpatel commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this.CUSTOM_CHECKBOX_STYLE = DwtCheckbox.CUSTOM_CHECKBOX && this.INPUT_TYPE == 'checkbox';
Good point. Will update it. Thanks.

2017-04-13 05:22 UTC, kalpeshhpatel commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +
Fixed: https://github.com/Zimbra/zm-ajax/pull/4/files#diff-5d22f86ec071d8b2e4f423ae9803c185R382

2017-04-13 05:23 UTC, kalpeshhpatel commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this._inputIconEl.setAttribute(AjxEnv.isIE ? "htmlFor" : "for", this._inputEl.id);
No, not needed, I misplaced it. 
Updated code: https://github.com/Zimbra/zm-ajax/pull/4/files#diff-5d22f86ec071d8b2e4f423ae9803c185R355 Thanks for pointing it though.

2017-04-13 05:23 UTC, kalpeshhpatel commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this.CUSTOM_CHECKBOX_STYLE = DwtCheckbox.CUSTOM_CHECKBOX && this.INPUT_TYPE == 'checkbox';
Done: https://github.com/Zimbra/zm-ajax/pull/4/files#diff-5d22f86ec071d8b2e4f423ae9803c185R111 and https://github.com/Zimbra/zm-ajax/pull/4/files#diff-5d22f86ec071d8b2e4f423ae9803c185R340

2017-04-13 05:24 UTC, kalpeshhpatel commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +DwtCheckbox.prototype.__setCustomCheckboxIcon = function () {
Done: https://github.com/Zimbra/zm-ajax/pull/4/files#diff-5d22f86ec071d8b2e4f423ae9803c185R387

2017-04-13 09:38 UTC, tarangkhandelwal approved these changes
Looks good to me.

2017-04-13 10:00 UTC, SatyamKumarOnline approved these changes

2017-04-13 10:00 UTC, SatyamKumarOnline commented on WebRoot/js/ajax/dwt/widgets/DwtCheckbox.js
> +	this.CUSTOM_CHECKBOX_STYLE = this.CUSTOM_CHECKBOX && this.INPUT_TYPE == 'checkbox';
Can we have === , here

2017-04-13 10:01 UTC, silentsakky approved these changes

2017-04-13 10:07 UTC, merged